name: Build LaTeX PDF
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: >-
            scheme-small
            latexmk
            texlive-latex-recommended
            texlive-latex-extra
            texlive-fonts-recommended
      - run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex
      - uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: main.pdf
