name: Build LaTeX PDF
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # TeX のセットアップとビルドを一括でやってくれる安定版
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex          # これだけで latexmk を実行
          texlive_version: 2024
          # 念のため追加で取るパッケージ（IEEEtran 等）
          extra_packages: |
            latexmk
            IEEEtran
            bibtex

      - uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: main.pdf


