name: Build LaTeX PDF
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 安定版：LaTeX専用アクション（latexmkを内蔵）
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          texlive_version: 2024
          # 足りがちなパッケージを多めに明示
          extra_packages: |
            latexmk
            collection-latex
            collection-latexrecommended
            collection-latexextra
            collection-fontsrecommended
            collection-bibtexextra
            IEEEtran

      - uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: main.pdf



