name: Build LaTeX PDF
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          docker_image: texlive/texlive:latest
          # ← ここで不足しがちなものを明示インストール
          pre_compile: |
            tlmgr update --self --all
            tlmgr install IEEEtran collection-bibtexextra latexmk
          args: -pdf -interaction=nonstopmode -halt-on-error -file-line-error

      - uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: main.pdf
