name: Build LaTeX PDF
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ← TeX Live は「collection-◯◯」名を使うのが正解
      - uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-small
            collection-latex
            collection-latexrecommended
            collection-latexextra
            collection-fontsrecommended
            collection-bibtexextra

      - run: |
          latexmk -pdf -interaction=nonstopmode -halt-on-error -file-line-error main.tex

      - uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: main.pdf

